# Generated by Django 6.1 on 2026-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance_pending', 'Advance Pending'), ('partially_paid', 'Partially Paid'), ('pre_paid', 'Pre Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='advance_pending', max_length=30),
        ),
    ]
