# Generated by Django 6.1 on 2026-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentdetail',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
