# Generated by Django 6.1 on 2026-09-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='straptype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='strap-type/'),
        ),
        migrations.AddField(
            model_name='watchtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watch-type/'),
        ),
    ]
